apiVersion: v1
kind: Service
metadata:
  name: quipus-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "09723aed-e463-4ff3-b60e-cdae432658a2"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  - port: 6001
    targetPort: 6001
    name: 'websocket'
  selector:
    app: quipus
  type: LoadBalancer
